apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:X+OGLMgShzeUnuL4a8CXCdui7kmqiT789RmhhRo/nrg2adq1aNZrZD08PXpbuVzEVA47vh06pzom7g24G2gMIgNSAMItmTrXcazeB5d/STJULKXGOznG98gSonLkj7micrOS+odno/FVF078Hpe0WUmK6UmJLMwtY09zNqFQSVEtaCupX/aihSRcm3S/6FXEKyxj7C4pFbMFs0Mi1l2PuxlABVZvRgv5qrsDQEffDFQj4GvJhcuhl4VUOUKzo2ruXacZPccRoTdETGsiyNAnWj0YhSeSAGaEyFxh7h5cRjAxom2hEs7ND9DULwUiIq4YQrU6gupiuGQnrr2JrT98GisHBp789MRreSjK4OgR5hyISyn8iq7oN5L8iTxPKz2L,iv:wu9dL37wfS8sQbaf8bSAsPCGE3KlR+FH4ex3cGsRYyI=,tag:DxInPBb1b75mTZYLotR1kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:O2jlqDwmSMK9RPkFipo/ayaK1jF+t4j4KBw80uqvpUVizZsONKCILm4BJeMQCqJp8DvuluWBPu3dl/RWIz++fiL6zqbF7dYzxk7VAIr97PbrUDaDi0vbdX6PirEHmMens8cVlQ+OR19DmTyaymSWOvWbuKgMRp9b7hjCU8TXOMW20cDoEjwtusnOVSqgf5aUnnD5E/PGUgvepYXDaCP8Gf95V/0CaF/XL6XkI/BYxeQ9g86rSTdDv/YQ5YkQL0iFhNiF5ouaiGrm72pgww==,iv:qSRXPeWWcpVGlKE/qinKKTSBrTSsE6AtloEMXT5Y2Vc=,tag:4IhB5uTTVNh1VA2QyAzQnw==,type:str]
    known_hosts: ENC[AES256_GCM,data:RMFXOUSl55SALaprZKST2CFyCXibMYDDWZCtEVWUc557JR+4z60vte04h2zaSGfVtIQy8aH6rF1hcCkPyMfRa79RPEPbxdDs4JGuKBgQc0ZgvX8uWfE0wo8CRF24cvGM6QLvER9FZ9t2cyabv76Hcb3GZdNT26i2TbrR5l4xrg85DyHoWM/Fb2oSSIH7GeH0rqo0gpcphdjjK6YKLcAD+gwLrlVm1gi1aZgb,iv:3shEAWI6B9HogE6GzoCkgYJPnXLuPgona1xpr5MEL08=,tag:RcgMA1Jo50h2Wmuf50pcng==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u0d8mmt6zm570dyzke7f2z3rj068hmcltfkvve7qvx5jd78cpgeskcxmnv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM1RVamFPM2JuOGVtd3JT
            UzFZWFAyUUFDZzJLOC9iSFRJS3JnT3o2ekUwCnBPYW5xWWlTYVZGejYyVXpzY1pB
            bllHMUlEV3MzS2NkeEVjNm5WS0JlL2cKLS0tIDRUOHNQL1lpNlpzcGJpSE9nTzVM
            b056VmdGWDNGQzR4bGJJNkFkcHgxaWcKy9ohDmXl5m9hNNJhhl4kwvmiIZ4xCQ1/
            OEaDZlh3880CQt0jaMOoifVSD8I6u2wp23uaprACyeHYrPmxnZs+Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T19:00:19Z"
    mac: ENC[AES256_GCM,data:YBaCm8/M/jODzaPeFmYHL2JxUfnLCKgtsGzkqMMbmDVSp4Y5YHOPpT0pb+DBvzzxwSDzr0seitTqA+Z36l0feyF9AwIjE8h/5KoUQ7jeGkvGMTgrLNWzfVtaEs+Z8qS1hqocVpkwZRT+iZY74twGSONVz6ENe8R19tcSU0BaB2Q=,iv:AMgmICvcYX08Eze0UVPAkWpcuaklcHFhc6+9lRa9+wQ=,tag:2fmP1En7qcs+K2MK2A1duQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
