apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8nbh+VfGeddhrEDkiY/wZxfTNzBjpjbbiWkUkTCNd0ZLf3tANX3WPoy21TLJF/mHFdNZI1qXgFbS643IqitvwuJhzruvReaWHk50bUkyN1U4rACfsl72yb8U9GvhyH7OGJYD9aedhNf6fBJkrB1pgZd/Mu0mARhUMFfeRbOM/aUmNdSDP9a1DYPLAedxmPbG53wPO1SExj9M5vgjiz8lm4gpvOmsgjYLfcnYdKpPEwxK8dSO5YM30a8JbTpIA9JupKm9Br90O9ZTZE0w0i2XHOh/4/1Ua3i0iAtPfIl2apjhMctoMDXfwe/pE5Rv1q0kOFx/E0I0bDgTrliQ87huBErZDuhYrx+ipbmaABVoJABkaxQw/qEV6Eomg24oMqGI,iv:SB1lw1wcb4mT8UQ5VifktIyWne/JEoonma88dYx8+uI=,tag:DlOdB0Ea+185XDvkDVnwQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:T1bsRpuNJWyoLIcVsgfD7O0gk4Rvis3Ja+iSh8gwqqO8AWGZgAGuyRWhN41fWsMyV7IT65iY0t7hWf7P8cQeXi28U4ustFCIqTKAS3bqMKz24JojkY1d/oTu3iyQRU3k6EW2pcZt5iAlnT2VLo1SNdkMDdxZIDCVHFOLIy335BP/d+9JL5Yp5lEOWEal9SB2R9fZMRH4RVL/sIPdTanHxmZPMCOHBoi/fLk2lmaqxfdNImIbZ9recOnOn0EHE+uTn9MOgpCiGJHFZadPCA==,iv:/VVJn4sZHDYvJsYmZjXK7VzyZYj+mFgwOLuslk5T4ys=,tag:tYbnVk6F+rMpTU5ZzFJFew==,type:str]
    known_hosts: ENC[AES256_GCM,data:bZJzhJIVdG8ny06ujyYrE9I7jYQSrQ3wwMlNJ0tsnckmmMyRCrr2NIJb7uIRVQsQw/PIsSNlVz7+KCASgk6W/UmrJBpwZmAd6lHLDl4fL07W9vTcfsWPmCXMB4QQI3bu29Ir+uFd2+5fRqV+NtLuhseBrc0K/cRAXcMlMSnzSkvwqzUjJB5YyVS0uIoHx3F+FNSZSExvz6V9RYKiFeahbyw0lMq9tlIQF78M,iv:nGZEIp5+yftMn6kJZ/c5YueDs+YmMWqCZjtGW7n7Yk8=,tag:RDojaVpKCNUIIY1rmbHaig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u0d8mmt6zm570dyzke7f2z3rj068hmcltfkvve7qvx5jd78cpgeskcxmnv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bW1QUGdZUlkyY1AyMHZs
            RS9DdjZFdE96RUpjWVV6Q2RwUjA0OGp2eldZCmJNOWNhb2hrOWw0dFo3WWg0NUpC
            ZVJXT1hFaHpMbjVjSlUxY0QzNXpJNVEKLS0tIFZwS2ZZSVVQN0IzM3c1WkNCZ0JU
            SWlyZFdvdENEdXlQUDhmeTY4c09SMEUK3WJYxJlm7V783yFiBB4NqE8lofBC9p3k
            BnAdbk6/e2Ok+Ra31n+cEjzF6rzLRnrs9BEHOpwZc/w310BjPLdU7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T20:28:29Z"
    mac: ENC[AES256_GCM,data:ATzlzov9WjZZNzG3C+r46Ro2W/SmNerCb9QJov/hXt0sLWSRfsLpiiln3MS2VMgNY2bHXiwWRvYUzB/AhS0bIUmsNb73niNue8BkptYbVumrm+DRvy89C+3IWSP5H75dF0AWhL/k3u8isr2yGNkrk/l/F5jF6o2ntWSdtciRS6A=,iv:6jVX59JxGDRxtBzgy+s6gWqpIi2rIqqk2ZH5QWbKjq4=,tag:T8jf35Kj05mlsr1VjvF6fg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
